global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fake-services'
    dns_sd_configs:
      - names:
          - 'fake-service-1'
          - 'fake-service-2'
        type: 'A'
        port: 80
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_dns_name]
        target_label: service_name
